### ISSUE TITLE
FSL version

### ISSUE THREAD

**Issue by mgxd** [BIDS-Apps/HCPPipelines#14]
Reading WashU's [HCP Pipelines documentation](https://github.com/Washington-University/Pipelines/wiki/v3.4.0-Release-Notes%2C-Installation%2C-and-Usage#prerequisites), FSL 5.0.6 is recommended, as 5.0.7+ cause the Task Analysis to fail. However, the Dockerfile is building FSL 5.0.9, is this intended?

**Comment by alexlicohen** [comment]
See this from Tim Brown a while ago:
(I'm pretty sure 5.0.9+ will work for everything, but if you want to
replicate HCP results, I believe you have to dig up the 5.0.6 version...

-Alex


How do the pipelines choose between fsl versions? Or is it up to the user
to prepare their path appropriately based on what pipeline they'll be
running?

-M


> From: "Timothy B. Brown" <tbbrown@wustl.edu>
>
> Hi Michael,
>
> Unfortunately, the situation gets a little "messy". The prerequisites
> for v3.19.0 are (for the most part) the same as those for v3.4.0.
> However, due to a change that was introduced in FSL at version 5.0.7
> that is not backward compatible, there are some specific pipelines that
> require different versions of FSL.
>
> For the most part, FSL 5.0.6 is required to get results that are
> compatible with the HCP results. But for the diffusion preprocessing
> pipeline, you will need FSL version 5.0.9.  In fact, we actually used a
> version of the eddy program that is to be included in 5.0.10 (which I do
> not believe is officially released just yet.) See the message here
> (https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;5ade7210.1611) for
> some information on how to create a "patched" version of 5.0.9 that
> contains the 5.0.10 version of the eddy program.
>
> For the ReApplyFix pipeline, you will also need version 5.0.9. (Since it
> does not use the eddy program, it does not matter if this is the
> actually released v5.0.9 or one that is "patched" to include the 5.0.10
> version of eddy.) Since the DeDriftAndResample pipeline invokes the
> ReApplyFix pipeline, it requires FSL version 5.0.9.
>
> I have tried to include specific version checks and warnings in any
> pipelines that specifically require v5.0.9 or above.
>
> I am in the process of trying to get or verify that all the pipelines in
> entire product can use the same version of FSL (v5.0.9+), but I had to
> maintain some of them in the FSL v5.0.6 state to make sure all our HCP
> data was processed the same way.
>
> Wish I had a simpler answer for you,
>
>    Tim



----------------------------------------------------------------
Alexander Li Cohen, M.D., Ph.D.
E-mail: Alexander.Cohen2@childrens.harvard.edu (Medical/Science Email)
E-mail: alexcohen@gmail.com (Lifetime Email)
----------------------------------------------------------------

On Thu, Apr 13, 2017 at 3:39 PM, Mathias Goncalves <notifications@github.com

**Comment by mgxd** [comment]
@alexlicohen ah, good to hear - thanks for sharing!
