### ISSUE TITLE
Type error in the pre freesurfer step

### ISSUE THREAD

**Issue by sharonhanc** [BIDS-Apps/HCPPipelines#17]
I got an error when using the freeSurfer pipeline that should not be too difficult to fix. If there is no fieldmap for the T1/T2, the parameters are set to "NONE" which generates the error in the function run_pre_freesurfer(). The function requires integer and not string parameters.

**Comment by chrisfilo** [comment]
What is the exact traceback of the error you are getting?

**Comment by rhancockn** [comment]
Closing old issues that are likely no longer applicable.
