### ISSUE TITLE
Error in finding an MNI template (MNI152_T1_1.0mm)

### ISSUE THREAD

**Issue by mfalahpour** [BIDS-Apps/HCPPipelines#18]
Hi,
I'm trying to run the HCPpipeline on one of our servers and I get the following error message:

Image Exception : #22 :: ERROR: Could not open image /opt/HCP-Pipelines/global/templates/MNI152_T1_1.0mm
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
/opt/HCP-Pipelines/PreFreeSurfer/scripts/ACPCAlignment.sh: line 84:  2598 Aborted                 (core dumped) ${FSLDIR}/bin/flirt -interp spline -in "$WD"/robustroi.nii.gz -ref "$Reference" -omat "$WD"/roi2std.mat -out "$WD"/acpc_final.nii.gz -searchrx -30 30 -searchry -30 30 -searchrz -30 30

In the output directory, 3 new directories (MNINonLinear, T1w and T2w) are generated and the T1 files are also copied, but the xfms directories within them is empty.

Any idea on what may cause the issue and how I can fix it?

**Comment by chrisfilo** [comment]
This error was suppose to be fixed in v3.17.0-14. Which version are you using?

**Comment by mfalahpour** [comment]
Thanks for the quick response. I am using version v3.17.0-13.
How can I switch the newer version?

**Comment by chrisfilo** [comment]
Use `bids/hcppipelines:v3.17.0-13` instead of `bids/hcppipelines:v3.17.0-13` in your command. Let me know if this worked so we could close this issue.

**Comment by mfalahpour** [comment]
Thanks!
I was not specifying the version number before...it was pulling v3.17.0-13 by default. 
Switching to the new version did solve the issue.. Thanks again!
