### ISSUE TITLE
Using the {participant} level mode

### ISSUE THREAD

**Issue by paola-o** [BIDS-Apps/HCPPipelines#19]
Hello,

I am trying to optimize my usage of this amazing tool and take advantage of parallelization on my university's server system. So far, I've been running the script in "participant level mode (for one participant)", but I have several cores available, and I need to run about 60 subjects or so. 

Aside from specifying the "-n_cpus", how can I use the "{participant}" positional argument? Would this help with parallelization?  What are the options other than "participant" that argument will accept?

Thanks in advance for your help!

Best,
Paola

**Comment by jokedurnez** [comment]
Hi Paola,
Not sure if this is solved, but in case someone else is running into this... I'm assuming you use a HPC for these analyses.  How I 'parallelise' is by running 1 job per subject, by specifying `--participant label` in each job.

**Comment by paola-o** [comment]
Thanks for your response, Joke! Yes, I'm running on an HPC and have also been running 1 job per subject, with multiple subjects in parallel.  I just wanted to make sure that is the optimal way to run this process, rather than including multiple subjects in one job and parallelizing some other way.
