### ISSUE TITLE
circle CI data

### ISSUE THREAD

**Issue by jokedurnez** [BIDS-Apps/HCPPipelines#21]
Hi,

Not sure where to ask this question...
I've been working on this app, and I had to update the bids-validator.  Unfortunately now the test data is not compatible anymore with the validator (there is no file dataset_description.json).  How can I change the test data on osf?

@chrisfilo @oesteban 

Joke

**Comment by chrisfilo** [comment]
I added you as a contributor on OSF (you should get an email) - thank you
for working on this!

Best,
Chris
