### ISSUE TITLE
Error with fMRI Volume

### ISSUE THREAD

**Issue by tjhendrickson** [BIDS-Apps/HCPPipelines#25]
Hello,

I am running into a fatal error that I cannot quite track down how to alleviate. I start the fMRIVolume processing step. The script gets to the "DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh" and then an error message is sent to the screen:

Traceback (most recent call last):
  File "/run.py", line 410, in <module>
    stage_func()
  File "/run.py", line 139, in run_generic_fMRI_volume_processsing
    run(cmd, cwd=args["path"], env={"OMP_NUM_THREADS": str(args["n_cpus"])})
  File "/run.py", line 29, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1

This is the command that I typed: 

 docker run -v /home/timothy/sandbox_DO_NOT_DELETE/BIDS/263_ETOH_BIDS/local:/bids_dataset:ro -v /home/timothy/sandbox_DO_NOT_DELETE/BIDS/263_ETOH_BIDS/hcp_output/:/outputs bids/hcppipelines /bids_dataset /outputs participant --participant_label 8404 --stages fMRIVolume --n_cpus 1 --license_key 27185

**Comment by rhancockn** [comment]
Closing old issues that are likely no longer applicable.
