### ISSUE TITLE
ENH: Removing all the empty lines from the stdout?

### ISSUE THREAD

**Issue by pvelasco** [BIDS-Apps/HCPPipelines#34]
Hi,

Is there a reason to have an empty line between each stdout line?  E.g.:

> [...]
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: GEB0InputName: NONE
>
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: TE: NONE
> 
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: SpinEchoPhaseEncodeNegative: NONE
> 
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: SpinEchoPhaseEncodePositive: NONE
> 
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: DwellTime: NONE
> 
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: SEUnwarpDir: NONE
> 
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: T1wSampleSpacing: NONE
> 
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: T2wSampleSpacing: NONE
> 
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: UnwarpDir: NONE
> 
> [...]

I suggest telling `print` not to add a newline every time it prints out, by simply changing the following line:
https://github.com/BIDS-Apps/HCPPipelines/blob/1650b0575490e05ebd1d673030c0a03ad76d6586/run.py#L25

to:
```
print(line, end='')
```

That way the output looks like:

> [...]
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: GEB0InputName: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: TE: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: SpinEchoPhaseEncodeNegative: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: SpinEchoPhaseEncodePositive: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: DwellTime: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: SEUnwarpDir: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: T1wSampleSpacing: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: T2wSampleSpacing: NONE
> Thu Aug  9 15:37:38 UTC 2018 - PreFreeSurferPipeline.sh: UnwarpDir: NONE
> [...]

**Comment by chrisfilo** [comment]
Would you mind sending a Pull Request?
