### ISSUE TITLE
No module named 'conda' error on docker build

### ISSUE THREAD

**Issue by HaukeBartsch** [BIDS-Apps/HCPPipelines#46]
I am trying to docker build:
     docker build -t bids/hcppipelines -f Dockerfile  .
on MacOS and I get the following error:

...
The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0                              --> 2019.9.11-hecc5488_0 conda-forge
    certifi:         2018.4.16-py27_0                          --> 2019.9.11-py37_0     conda-forge
    libffi:          3.2.1-hd88cf55_4                          --> 3.2.1-he1b5a44_1006  conda-forge
    libgcc-ng:       7.2.0-hdf63c60_3                          --> 9.1.0-hdf63c60_0                
    libstdcxx-ng:    7.2.0-hdf63c60_3                          --> 9.1.0-hdf63c60_0                
    ncurses:         6.1-hf484d3e_0                            --> 6.1-hf484d3e_1002    conda-forge
    openssl:         1.0.2o-h20670df_0                         --> 1.1.1c-h516909a_0    conda-forge
    pip:             10.0.1-py27_0                             --> 19.2.3-py37_0        conda-forge
    python:          2.7.15-h1571d57_0                         --> 3.7.3-h33d41f4_1     conda-forge
    readline:        7.0-ha6073c6_4                            --> 8.0-hf8c457e_0       conda-forge
    setuptools:      39.2.0-py27_0                             --> 41.2.0-py37_0        conda-forge
    six:             1.11.0-py27h5f960f1_1                     --> 1.12.0-py37_1000     conda-forge
    sqlite:          3.23.1-he433501_0                         --> 3.29.0-hcee41ef_1    conda-forge
    tk:              8.6.7-hc745277_3                          --> 8.6.9-hed695b0_1003  conda-forge
    wheel:           0.31.1-py27_0                             --> 0.33.6-py37_0        conda-forge
    zlib:            1.2.11-ha838bed_2                         --> 1.2.11-h516909a_1006 conda-forge

Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
The command '/bin/sh -c curl -fsSLO https://repo.continuum.io/miniconda/Miniconda2-4.5.4-Linux-x86_64.sh &&     bash Miniconda2-4.5.4-Linux-x86_64.sh -b -p /usr/local/miniconda &&     rm Miniconda2-4.5.4-Linux-x86_64.sh &&     conda config --add channels conda-forge &&     conda install -y mkl=2019.3 mkl-service=2.0.2 numpy=1.16.4 nibabel=2.4.1 pandas=0.24.2 && sync &&     conda clean -tipsy && sync &&     pip install --no-cache-dir pybids==0.9.1' returned a non-zero code: 1

**Comment by HaukeBartsch** [comment]
FYI: the error seems to be caused by:

> conda clean -tipsy
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

I can run all other commands in that section just fine.

**Comment by rhancockn** [comment]
Closing old issues that are likely no longer applicable.
