### ISSUE TITLE
Please update to v4.1.2 which features all the flashy new stuff

### ISSUE THREAD

**Issue by yarikoptic** [BIDS-Apps/HCPPipelines#51]
Thank you very much in advance!

NB possibly related: https://github.com/Washington-University/HCPpipelines/issues/162

Note that I see the tags in this repo for recentish releases (v4.0.0-1), but for some reason http://bids-apps.neuroimaging.io/apps/ shows only v3.17.0-18 . So there might be some need to fix up something on bids-apps side... haven't looked into it yet

**Comment by rhancockn** [comment]
Will get working on it with the recent 4.1.3 release, which has ALL the flashy things! 

The current repo is indeed based on the patched 4.0 series.

**Comment by yarikoptic** [comment]
Thank you in advance!!!!

**Comment by yarikoptic** [comment]
so the 4.1.3 is out, could bids-app be updated?
