### ISSUE TITLE
list type for "IntendedFor" field

### ISSUE THREAD

**Issue by yeunkim** [BIDS-Apps/HCPPipelines#6]
In bids/hcppipelines:v3.17.0-12, there is an error when there is more than one target scan for a fieldmap:

Traceback (most recent call last):
  File "/run.py", line 239, in <module>
    fieldmap_set = layout.get_fieldmap(t1ws[0])
  File "/usr/local/lib/python2.7/dist-packages/bids/grabbids/bids_layout.py", line 70, in get_fieldmap
    if path.endswith(metadata["IntendedFor"]):
TypeError: endswith first arg must be str, unicode, or tuple, not list

---------------------------------------
FYI: In the JSON file: "IntendedFor": ["func/sub-01_task-emotionregulation_run-01_bold.nii.gz", "func/sub-01_task-rest_run-01_bold.nii.gz"]

This passes the bids-validator as BIDS compliant. 

Example log file is attached.

[log1102.txt](https://github.com/BIDS-Apps/HCPPipelines/files/567793/log1102.txt)

Thanks!

**Comment by chrisfilo** [comment]
Could you try v3.17.0-13?

**Comment by yeunkim** [comment]
Just tried it, and I got this error:

/usr/lib/node_modules/bids-validator/validators/headerFields.js:194
        var hdr2_val  = Number(hdr2[i].match(/-?\d*\.?\d*/));
                                      ^

TypeError: Cannot read property 'match' of undefined
    at headerFieldCompare (/usr/lib/node_modules/bids-validator/validators/headerFields.js:194:39)
    at headerField (/usr/lib/node_modules/bids-validator/validators/headerFields.js:158:56)
    at headerFields (/usr/lib/node_modules/bids-validator/validators/headerFields.js:23:22)
    at /usr/lib/node_modules/bids-validator/validators/bids.js:321:50
    at /usr/lib/node_modules/bids-validator/node_modules/async/lib/async.js:52:16
    at done (/usr/lib/node_modules/bids-validator/node_modules/async/lib/async.js:246:17)
    at /usr/lib/node_modules/bids-validator/node_modules/async/lib/async.js:44:16
    at /usr/lib/node_modules/bids-validator/validators/bids.js:285:33
    at NIFTI (/usr/lib/node_modules/bids-validator/validators/nii.js:234:5)
    at /usr/lib/node_modules/bids-validator/validators/bids.js:283:29

Traceback (most recent call last):
  File "/run.py", line 206, in <module>
    run("bids-validator " + args.bids_dir)
  File "/run.py", line 28, in run
    raise Exception("Non zero return code: %d"%process.returncode)
Exception: Non zero return code: 1

**Comment by chrisfilo** [comment]
Interesting. A similar issue with the validator was reported previously: https://github.com/INCF/bids-validator/issues/227 but it was supposed to be fixed. It's weird that you did not run into this when you tried v3.17.0-12. Did you change anything about the input dataset between trying v3.17.0-12 and v3.17.0-13?

**Comment by yeunkim** [comment]
I think the type of error is similar, but the origin is different. It was my mistake (no error in the code), there was a typo in the mount directory folder when I invoked the command. It runs fine after the fix.

Thanks again Chris!
